from app.backend.services.ai_service import ai_service
from app.backend.services.temporal_service import temporal_service
from app.backend.services.fusion_service import fusion_service
from app.backend.services.anomaly_service import anomaly_service
from app.backend.services.geospatial_service import geospatial_service
from app.backend.services.xai_service import xai_service
from app.backend.services.mission_service import mission_service
from app.backend.services.irrigation_service import irrigation_service
from app.backend.services.digital_twin_service import digital_twin_service
